create extension if not exists "pgcrypto";

create table if not exists public.usuarios (
  id uuid primary key references auth.users(id) on delete cascade,
  nome text not null,
  email text not null unique,
  tipo text not null check (tipo in ('Administrador', 'Professor', 'Avaliador', 'Aluno')),
  ativo boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.areas_conhecimento (
  id bigint generated by default as identity primary key,
  nome text not null unique
);

create table if not exists public.projetos (
  id bigint generated by default as identity primary key,
  ano integer not null,
  titulo text not null,
  area_id bigint references public.areas_conhecimento(id),
  orientador text not null,
  coorientador text,
  created_at timestamptz not null default now()
);

create table if not exists public.alunos (
  id bigint generated by default as identity primary key,
  nome text not null
);

create table if not exists public.projeto_alunos (
  projeto_id bigint references public.projetos(id) on delete cascade,
  aluno_id bigint references public.alunos(id) on delete cascade,
  primary key (projeto_id, aluno_id)
);

create table if not exists public.criterios (
  id bigint generated by default as identity primary key,
  descricao text not null,
  peso numeric(5,2) not null default 1 check (peso > 0)
);

create table if not exists public.avaliacoes (
  id bigint generated by default as identity primary key,
  projeto_id bigint not null references public.projetos(id) on delete cascade,
  avaliador_id uuid not null references public.usuarios(id),
  data date not null default current_date,
  unique (projeto_id, avaliador_id)
);

create table if not exists public.notas (
  avaliacao_id bigint references public.avaliacoes(id) on delete cascade,
  criterio_id bigint references public.criterios(id) on delete cascade,
  nota numeric(4,2) not null check (nota >= 0 and nota <= 10),
  primary key (avaliacao_id, criterio_id)
);

insert into public.areas_conhecimento (nome) values
  ('Ciências Biológicas'),
  ('Ciências da Saúde'),
  ('Ciências Exatas e da Terra'),
  ('Ciências Humanas'),
  ('Ciências Agrárias'),
  ('Ciências Sociais Aplicadas'),
  ('Engenharias'),
  ('Linguística, Letras e Artes')
on conflict (nome) do nothing;

insert into public.criterios (descricao, peso) values
  ('Clareza na apresentação', 1),
  ('Rigor científico', 2),
  ('Criatividade e inovação', 1.5),
  ('Relevância social', 1),
  ('Organização do projeto', 1)
on conflict do nothing;

create or replace function public.get_tipo_usuario()
returns text
language sql
security definer
set search_path = public
as $$
  select tipo from public.usuarios where id = auth.uid() and ativo = true;
$$;

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select coalesce(public.get_tipo_usuario() = 'Administrador', false);
$$;

alter table public.usuarios enable row level security;
alter table public.areas_conhecimento enable row level security;
alter table public.projetos enable row level security;
alter table public.alunos enable row level security;
alter table public.projeto_alunos enable row level security;
alter table public.criterios enable row level security;
alter table public.avaliacoes enable row level security;
alter table public.notas enable row level security;

create policy "usuarios_select_autenticados" on public.usuarios
for select to authenticated using (public.is_admin() or id = auth.uid());
create policy "usuarios_admin_all" on public.usuarios
for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "areas_select_todos" on public.areas_conhecimento
for select to authenticated using (true);
create policy "areas_admin_all" on public.areas_conhecimento
for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "projetos_select_todos" on public.projetos
for select to authenticated using (true);
create policy "projetos_admin_all" on public.projetos
for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "projetos_professor_insert" on public.projetos
for insert to authenticated with check (public.get_tipo_usuario() in ('Professor', 'Administrador'));
create policy "projetos_professor_update" on public.projetos
for update to authenticated using (public.get_tipo_usuario() in ('Professor', 'Administrador'))
with check (public.get_tipo_usuario() in ('Professor', 'Administrador'));

create policy "alunos_select_todos" on public.alunos
for select to authenticated using (true);
create policy "alunos_admin_professor_all" on public.alunos
for all to authenticated using (public.get_tipo_usuario() in ('Administrador', 'Professor'))
with check (public.get_tipo_usuario() in ('Administrador', 'Professor'));

create policy "projeto_alunos_select_todos" on public.projeto_alunos
for select to authenticated using (true);
create policy "projeto_alunos_admin_professor_all" on public.projeto_alunos
for all to authenticated using (public.get_tipo_usuario() in ('Administrador', 'Professor'))
with check (public.get_tipo_usuario() in ('Administrador', 'Professor'));

create policy "criterios_select_todos" on public.criterios
for select to authenticated using (true);
create policy "criterios_admin_all" on public.criterios
for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "avaliacoes_select_todos" on public.avaliacoes
for select to authenticated using (true);
create policy "avaliacoes_admin_all" on public.avaliacoes
for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "avaliacoes_avaliador_insert" on public.avaliacoes
for insert to authenticated with check (
  public.get_tipo_usuario() in ('Avaliador', 'Administrador') and avaliador_id = auth.uid()
);
create policy "avaliacoes_avaliador_update" on public.avaliacoes
for update to authenticated using (
  public.get_tipo_usuario() in ('Avaliador', 'Administrador') and avaliador_id = auth.uid()
) with check (
  public.get_tipo_usuario() in ('Avaliador', 'Administrador') and avaliador_id = auth.uid()
);

create policy "notas_select_todos" on public.notas
for select to authenticated using (true);
create policy "notas_admin_all" on public.notas
for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "notas_avaliador_all" on public.notas
for all to authenticated using (
  exists (
    select 1 from public.avaliacoes a
    where a.id = avaliacao_id and a.avaliador_id = auth.uid()
  )
) with check (
  exists (
    select 1 from public.avaliacoes a
    where a.id = avaliacao_id and a.avaliador_id = auth.uid()
  )
);

insert into storage.buckets (id, name, public)
values ('feceac', 'feceac', false)
on conflict (id) do nothing;

create policy "storage_feceac_select" on storage.objects
for select to authenticated using (bucket_id = 'feceac');

create policy "storage_feceac_admin_all" on storage.objects
for all to authenticated using (bucket_id = 'feceac' and public.is_admin())
with check (bucket_id = 'feceac' and public.is_admin());

create policy "storage_feceac_professor_insert" on storage.objects
for insert to authenticated with check (
  bucket_id = 'feceac' and public.get_tipo_usuario() in ('Administrador', 'Professor')
);
