create extension if not exists "pgcrypto";

create table if not exists public.usuarios (
  id uuid primary key references auth.users(id) on delete cascade,
  nome text not null,
  email text not null unique,
  tipo text not null check (tipo in ('Administrador', 'Professor', 'Avaliador', 'Aluno')),
  ativo boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.tipos_projeto (
  id bigint generated by default as identity primary key,
  nome text not null unique
);

create table if not exists public.areas_conhecimento (
  id bigint generated by default as identity primary key,
  nome text not null unique,
  tipo_projeto_id bigint references public.tipos_projeto(id)
);

create table if not exists public.projetos (
  id bigint generated by default as identity primary key,
  ano integer not null,
  titulo text not null,
  area_id bigint references public.areas_conhecimento(id),
  tipo_projeto_id bigint references public.tipos_projeto(id),
  orientador text not null,
  coorientador text,
  created_at timestamptz not null default now()
);

create table if not exists public.alunos (
  id bigint generated by default as identity primary key,
  nome text not null
);

create table if not exists public.projeto_alunos (
  projeto_id bigint references public.projetos(id) on delete cascade,
  aluno_id bigint references public.alunos(id) on delete cascade,
  primary key (projeto_id, aluno_id)
);

create table if not exists public.criterios (
  id bigint generated by default as identity primary key,
  descricao text not null,
  peso numeric(5,2) not null default 1 check (peso > 0),
  observacoes text,
  tipo_projeto_id bigint references public.tipos_projeto(id)
);

create table if not exists public.avaliacoes (
  id bigint generated by default as identity primary key,
  projeto_id bigint not null references public.projetos(id) on delete cascade,
  avaliador_id uuid not null references public.usuarios(id),
  data date not null default current_date,
  unique (projeto_id, avaliador_id)
);

create table if not exists public.notas (
  avaliacao_id bigint references public.avaliacoes(id) on delete cascade,
  criterio_id bigint references public.criterios(id) on delete cascade,
  nota numeric(4,2) not null check (nota >= 0 and nota <= 10),
  primary key (avaliacao_id, criterio_id)
);

insert into public.tipos_projeto (nome) values
  ('Feira de Ciências'),
  ('Mostra Cultural')
on conflict (nome) do nothing;

insert into public.areas_conhecimento (nome) values
  ('Ciências Biológicas'),
  ('Ciências da Saúde'),
  ('Ciências Exatas e da Terra'),
  ('Ciências Humanas'),
  ('Ciências Agrárias'),
  ('Ciências Sociais Aplicadas'),
  ('Engenharias'),
  ('Linguística, Letras e Artes')
on conflict (nome) do nothing;

insert into public.criterios (descricao, peso, observacoes, tipo_projeto_id)
values
  ('Uso da Metodologia Científica', 3,
   '• O problema é apresentado de forma clara e precisa?
• Se o uso de amostras de controle for necessário, o estudante soube descobrir esta necessidade? Ele utilizou esta informação de forma correta?
• As informações coletadas foram suficientes para sustentar as conclusões apresentadas?
• A solução é plausível em relação ao problema estudado? Como foi o processo para se chegar nessa solução?
• Os dados coletados e os resultados da pesquisa foram adequadamente apresentados e analisados? A conclusão apresentada é coerente com os objetivos, hipótese e resultados?
• O estudante possui planos de continuar o projeto? Se sim, qual seria a próxima fase?', 1),
  ('Criatividade e Inovação', 3,
   '• O trabalho demonstra habilidade criativa e originalidade?
• A solução proposta para o problema é inovadora?
• A análise e interpretação dos dados demonstram criatividade?
• O protótipo ou produto desenvolvido apresenta características inovadoras?
• Considerando a Educação Básica, qual o grau de inovação da solução apresentada?', 1),
  ('Atitude Científica e Habilidades', 2,
   '• O estudante demonstra entusiasmo e comprometimento com o projeto?
• Demonstra capacidade para analisar criticamente dados e informações?
• Compreende diferentes pontos de vista e situações novas?
• Reconhece os limites do próprio projeto?
• Consegue comparar sua experiência com trabalhos semelhantes?
• Demonstrou iniciativa, perseverança, planejamento e capacidade de articulação?
• Conseguiu envolver família, escola ou comunidade no desenvolvimento do projeto?', 1),
  ('Profundidade da Pesquisa', 2,
   '• O problema estudado foi resolvido?
• O estudante apresenta documentação do desenvolvimento do trabalho (diário de bordo, relatório)?
• A documentação registra detalhadamente as atividades realizadas?
• Há evidências de planejamento e organização?
• As dificuldades encontradas e suas soluções foram registradas?
• Existem comentários ou feedback do orientador?
• Houve atualizações regulares durante o desenvolvimento da pesquisa?', 1),
  ('Clareza e Objetividade na Exposição do Projeto', 1,
   '• Durante a apresentação o estudante demonstra segurança e domínio do conteúdo?
• A apresentação oral foi organizada e coerente?
• O material escrito demonstra conhecimento sobre o projeto?
• As etapas do desenvolvimento foram apresentadas de forma clara e organizada?', 1),
  ('Relevância Social e Ambiental', 1,
   '• O problema estudado está relacionado ao contexto social do estudante?
• O projeto possui potencial para transformar a realidade da comunidade?
• Foram adotadas práticas de reciclagem ou reutilização de materiais?
• O trabalho promove educação e conscientização ambiental?
• O projeto possui potencial de aplicação prática?', 1),
  ('Criatividade e Originalidade', 1,
   '• O trabalho apresenta uma proposta inovadora?
• A ideia desenvolvida é original e demonstra autenticidade?
• Os estudantes apresentaram soluções ou abordagens diferenciadas em relação ao tema?', 2),
  ('Fundamentação e Pesquisa', 1,
   '• Os estudantes demonstram domínio do tema apresentado?
• O trabalho evidencia pesquisa consistente sobre aspectos históricos, culturais, científicos ou tecnológicos relacionados ao tema?
• As informações apresentadas são claras, corretas e bem fundamentadas?', 2),
  ('Inclusão, Relevância Social e Ambiental', 1,
   '• O trabalho adotou práticas de reciclagem, reutilização ou uso consciente de materiais?
• O projeto valoriza a cultura local, regional, nacional ou outras manifestações culturais?
• O trabalho considera aspectos de acessibilidade e inclusão para diferentes públicos?
• A proposta demonstra relevância social e/ou ambiental?', 2),
  ('Impacto Visual e Qualidade Técnica', 1,
   '• O trabalho apresenta boa qualidade visual e organização estética?
• A apresentação desperta o interesse e a atenção do público?
• Os estudantes demonstram domínio das técnicas utilizadas (desenho, pintura, fotografia, música, maquete, protótipo, entre outras)?
• Os materiais e recursos empregados foram utilizados de forma adequada?', 2),
  ('Interdisciplinaridade', 1,
   '• O trabalho integra conhecimentos de diferentes áreas?
• As diferentes áreas do conhecimento estão articuladas de forma coerente?
• A interdisciplinaridade contribui para enriquecer a compreensão do tema e a qualidade da proposta?', 2)
on conflict do nothing;

create or replace function public.get_tipo_usuario()
returns text
language sql
security definer
set search_path = public
as $$
  select tipo from public.usuarios where id = auth.uid() and ativo = true;
$$;

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select coalesce(public.get_tipo_usuario() = 'Administrador', false);
$$;

alter table public.usuarios enable row level security;
alter table public.tipos_projeto enable row level security;
alter table public.areas_conhecimento enable row level security;
alter table public.projetos enable row level security;
alter table public.alunos enable row level security;
alter table public.projeto_alunos enable row level security;
alter table public.criterios enable row level security;
alter table public.avaliacoes enable row level security;
alter table public.notas enable row level security;

create policy "usuarios_select_autenticados" on public.usuarios
for select to authenticated using (public.is_admin() or id = auth.uid());
create policy "usuarios_admin_all" on public.usuarios
for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "areas_select_todos" on public.areas_conhecimento
for select to authenticated using (true);
create policy "areas_admin_all" on public.areas_conhecimento
for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "tipos_projeto_select_todos" on public.tipos_projeto
for select to authenticated using (true);
create policy "tipos_projeto_admin_all" on public.tipos_projeto
for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "projetos_select_todos" on public.projetos
for select to authenticated using (true);
create policy "projetos_admin_all" on public.projetos
for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "projetos_professor_insert" on public.projetos
for insert to authenticated with check (public.get_tipo_usuario() in ('Professor', 'Administrador'));
create policy "projetos_professor_update" on public.projetos
for update to authenticated using (public.get_tipo_usuario() in ('Professor', 'Administrador'))
with check (public.get_tipo_usuario() in ('Professor', 'Administrador'));

create policy "alunos_select_todos" on public.alunos
for select to authenticated using (true);
create policy "alunos_admin_professor_all" on public.alunos
for all to authenticated using (public.get_tipo_usuario() in ('Administrador', 'Professor'))
with check (public.get_tipo_usuario() in ('Administrador', 'Professor'));

create policy "projeto_alunos_select_todos" on public.projeto_alunos
for select to authenticated using (true);
create policy "projeto_alunos_admin_professor_all" on public.projeto_alunos
for all to authenticated using (public.get_tipo_usuario() in ('Administrador', 'Professor'))
with check (public.get_tipo_usuario() in ('Administrador', 'Professor'));

create policy "criterios_select_todos" on public.criterios
for select to authenticated using (true);
create policy "criterios_admin_all" on public.criterios
for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "avaliacoes_select_todos" on public.avaliacoes
for select to authenticated using (true);
create policy "avaliacoes_admin_all" on public.avaliacoes
for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "avaliacoes_avaliador_insert" on public.avaliacoes
for insert to authenticated with check (
  public.get_tipo_usuario() in ('Avaliador', 'Administrador', 'Professor') and avaliador_id = auth.uid()
);
create policy "avaliacoes_avaliador_update" on public.avaliacoes
for update to authenticated using (
  public.get_tipo_usuario() in ('Avaliador', 'Administrador', 'Professor') and avaliador_id = auth.uid()
) with check (
  public.get_tipo_usuario() in ('Avaliador', 'Administrador', 'Professor') and avaliador_id = auth.uid()
);

create policy "notas_select_todos" on public.notas
for select to authenticated using (true);
create policy "notas_admin_all" on public.notas
for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "notas_avaliador_all" on public.notas
for all to authenticated using (
  exists (
    select 1 from public.avaliacoes a
    where a.id = avaliacao_id and a.avaliador_id = auth.uid()
  )
) with check (
  exists (
    select 1 from public.avaliacoes a
    where a.id = avaliacao_id and a.avaliador_id = auth.uid()
  )
);

insert into storage.buckets (id, name, public)
values ('feceac', 'feceac', false)
on conflict (id) do nothing;

create policy "storage_feceac_select" on storage.objects
for select to authenticated using (bucket_id = 'feceac');

create policy "storage_feceac_admin_all" on storage.objects
for all to authenticated using (bucket_id = 'feceac' and public.is_admin())
with check (bucket_id = 'feceac' and public.is_admin());

create policy "storage_feceac_professor_insert" on storage.objects
for insert to authenticated with check (
  bucket_id = 'feceac' and public.get_tipo_usuario() in ('Administrador', 'Professor')
);
