-- ============================================================
-- FECEAC - Migration: professores, alunos, projetos, areas, criterios
-- Executar no SQL Editor do Supabase
-- ============================================================

-- ============================================================
-- 1. PROFESSORES (nova tabela)
-- ============================================================
DROP TABLE IF EXISTS public.professores CASCADE;

CREATE TABLE public.professores (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  matricula text UNIQUE NOT NULL,
  nome text NOT NULL
);

ALTER TABLE public.professores ENABLE ROW LEVEL SECURITY;

CREATE POLICY "professores_select_todos" ON public.professores
FOR SELECT TO authenticated USING (true);
CREATE POLICY "professores_admin_all" ON public.professores
FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

INSERT INTO public.professores (id, matricula, nome) VALUES
  (1, '1442007', 'ADALBERTO BARBOSA JUNIOR'),
  (2, '1276620', 'ALDERI BATISTA PEREIRA'),
  (3, '1255525', 'ANA CELI ALVES DE LIMA'),
  (4, '1366386', 'ANA LUIZA GOMES BEZERRA'),
  (5, '1306880', 'ANA MARA ALVES DE FREITAS'),
  (6, '1283634', 'ANDEYERLLY DE PAIVA LIMA'),
  (7, '1394657', 'ANDREIA REBOUCAS LUZ DUNGA'),
  (8, '1353420', 'ANTONIA SELMA DE OLIVEIRA CAMARA'),
  (9, '1649760', 'ANTONIO EDMAR DE PALHARES'),
  (10, '1288857', 'AURELIO GOMES DA SILVA SEGUNDO'),
  (11, '1288954', 'CINTIA LUCIA SILVA FERREIRA CAETANO'),
  (12, '1235230', 'EBER MAIA DANTAS'),
  (13, '1431269', 'FERNANDO TASIO REGO DE OLIVEIRA'),
  (14, '1418661', 'FRANCELIA NUNES DE MEDEIROS FERREIRA'),
  (15, '1309552', 'FRANCISCO DE ASSIS VERISSIMO JUNIOR'),
  (16, '1203894', 'FRANCISCO JOSELITO DA SILVA'),
  (17, '1459961', 'FRANCISCO LAYLSON FREITAS DA COSTA'),
  (18, '1447335', 'GABRIELLA CRISTINA BATISTA DE ARAUJO'),
  (19, '2171694', 'GILNEIDE LUZIMAR DA SILVA'),
  (20, '1369172', 'GISELLY FERNANDES DE ALMEIDA'),
  (21, '1281283', 'GLORIA CRISTIANA DE OLIVEIRA MORAIS'),
  (22, '2009536', 'JOSE AILSON PEREIRA DE SOUSA'),
  (23, '1258460', 'JOSE ROBERTO DA SILVA'),
  (24, '1324063', 'JOSE WALTER DA SILVA'),
  (25, '2127210', 'KARLA RAFAELA MATIAS PAIVA'),
  (26, '1399551', 'KARLA RAPHAELA CARDOSO'),
  (27, '1362372', 'KELLYAN RODRIGUES FILGUEIRA'),
  (28, '1387219', 'LARA LILIANE HOLANDA'),
  (29, '1246984', 'LENILTON MAIA DE LIMA'),
  (30, '1420267', 'LUIZA BENTO DE QUEIROZ NETA'),
  (31, '1399551', 'MARA RENATA BARROS BARBOSA'),
  (32, '1295039', 'MARCIO TARCISIO MENDONCA FERREIRA'),
  (33, '1349082', 'MARCONDES MENEZES DE MELO'),
  (34, '1263609', 'MARIA VITORIA DE SOUZA'),
  (35, '1368427', 'MICHAEL PRATINI SILVA DE SOUZA'),
  (36, '1435078', 'MICHEL WIILLIAN ALVES'),
  (37, '1286250', 'REGINA LUCIA DE OLIVEIRA MATIAS'),
  (38, '1235877', 'ROBERTO ROSSINI CORDEIRO DE AMORIM'),
  (39, '1430530', 'SEBASTIAO LEONARDO MEDEIROS DE LUCENA'),
  (40, '1320475', 'TABITHA TALITHA COUTO MOURA'),
  (41, '1300075', 'TIAGO GLEIDSON DE LIMA BARRA'),
  (42, '1279327', 'TOMAZ GUILHERME PEREIRA DE SENA'),
  (43, '1366718', 'ULYSSES ARAUJO PINTO'),
  (44, '1444484', 'VANDO ROCHA DA SILVA'),
  (45, '1289225', 'VILCELANIA ALVES COSTA')
ON CONFLICT (matricula) DO NOTHING;

SELECT setval(pg_get_serial_sequence('public.professores', 'id'), 45);

-- ============================================================
-- 2. ALUNOS (adicionar colunas)
-- ============================================================
ALTER TABLE public.alunos ADD COLUMN IF NOT EXISTS matricula text;
ALTER TABLE public.alunos ADD COLUMN IF NOT EXISTS turma text;
ALTER TABLE public.alunos ADD COLUMN IF NOT EXISTS turno text;

-- ============================================================
-- 3. PROJETO_ALUNOS (adicionar turma)
-- ============================================================
ALTER TABLE public.projeto_alunos ADD COLUMN IF NOT EXISTS turma text;

-- ============================================================
-- 4. PROJETOS (migrar orientador/coorientador para FK)
-- ============================================================

-- Limpar dados existentes (serao reinseridos depois)
TRUNCATE public.notas CASCADE;
TRUNCATE public.avaliacoes CASCADE;
TRUNCATE public.projeto_alunos CASCADE;
TRUNCATE public.projetos CASCADE;

-- Drop policies antigas
DROP POLICY IF EXISTS "projetos_select_todos" ON public.projetos;
DROP POLICY IF EXISTS "projetos_admin_all" ON public.projetos;
DROP POLICY IF EXISTS "projetos_professor_insert" ON public.projetos;
DROP POLICY IF EXISTS "projetos_professor_update" ON public.projetos;

-- Drop colunas antigas e adicionar novas
ALTER TABLE public.projetos DROP COLUMN IF EXISTS orientador;
ALTER TABLE public.projetos DROP COLUMN IF EXISTS coorientador;
ALTER TABLE public.projetos ADD COLUMN IF NOT EXISTS orientador_id bigint NOT NULL;
ALTER TABLE public.projetos ADD COLUMN IF NOT EXISTS coorientador_id bigint;

-- Adicionar foreign keys
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'projetos_orientador_id_fkey') THEN
    ALTER TABLE public.projetos
      ADD CONSTRAINT projetos_orientador_id_fkey
      FOREIGN KEY (orientador_id) REFERENCES public.professores(id);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'projetos_coorientador_id_fkey') THEN
    ALTER TABLE public.projetos
      ADD CONSTRAINT projetos_coorientador_id_fkey
      FOREIGN KEY (coorientador_id) REFERENCES public.professores(id);
  END IF;
END $$;

-- Recriar policies
CREATE POLICY "projetos_select_todos" ON public.projetos
FOR SELECT TO authenticated USING (true);
CREATE POLICY "projetos_admin_all" ON public.projetos
FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "projetos_professor_insert" ON public.projetos
FOR INSERT TO authenticated WITH CHECK (public.get_tipo_usuario() IN ('Professor', 'Administrador'));
CREATE POLICY "projetos_professor_update" ON public.projetos
FOR UPDATE TO authenticated USING (public.get_tipo_usuario() IN ('Professor', 'Administrador'))
WITH CHECK (public.get_tipo_usuario() IN ('Professor', 'Administrador'));

-- ============================================================
-- 5. AREAS_CONHECIMENTO (atualizar dados)
-- ============================================================
DELETE FROM public.areas_conhecimento;

INSERT INTO public.areas_conhecimento (id, nome, tipo_projeto_id) VALUES
  (1, 'Ciencias Biologicas e da Saude', 1),
  (2, 'Exatas e Engenharia', 1),
  (3, 'Linguagens e suas Tecnologias', 1),
  (4, 'Ciencias Humanas e Sociais Aplicadas', 1),
  (5, 'Aplicativo', 2),
  (6, 'Artesanato', 2),
  (7, 'Cordel', 2),
  (8, 'Curta metragem', 2),
  (9, 'Desenho', 2),
  (10, 'Fotografia', 2),
  (11, 'Literatura', 2),
  (12, 'Maquete', 2),
  (13, 'Meio ambiente e sustentabilidade', 2),
  (14, 'Mural', 2),
  (15, 'Musica', 2),
  (16, 'Pintura', 2),
  (17, 'Poesia autoral', 2),
  (18, 'Prototipos', 2),
  (19, 'Outro', 2)
ON CONFLICT (nome) DO NOTHING;

SELECT setval(pg_get_serial_sequence('public.areas_conhecimento', 'id'), 19);

-- ============================================================
-- 6. CRITERIOS (atualizar dados)
-- ============================================================
DELETE FROM public.criterios;

INSERT INTO public.criterios (id, descricao, peso, observacoes, tipo_projeto_id) VALUES
  (1, 'Uso da Metodologia Cientifica', 3.00,
   E'• O problema e apresentado de forma clara e precisa?\n• Se o uso de amostras de controle for necessario, o estudante soube descobrir esta necessidade? Ele utilizou esta informacao de forma correta?\n• As informacoes coletadas foram suficientes para sustentar as conclusoes apresentadas?\n• A solucao e plausivel em relacao ao problema estudado? Como foi o processo para se chegar nessa solucao?\n• Os dados coletados e os resultados da pesquisa foram adequadamente apresentados e analisados? A conclusao apresentada e coerente com os objetivos, hipotese e resultados?\n• O estudante possui planos de continuar o projeto? Se sim, qual seria a proxima fase?',
   1),
  (2, 'Criatividade e Inovacao', 3.00,
   E'• O trabalho demonstra habilidade criativa e originalidade?\n• A solucao proposta para o problema e inovadora?\n• A analise e interpretacao dos dados demonstram criatividade?\n• O prototipo ou produto desenvolvido apresenta caracteristicas inovadoras?\n• Considerando a Educacao Basica, qual o grau de inovacao da solucao apresentada?',
   1),
  (3, 'Atitude Cientifica e Habilidades', 2.00,
   E'• O estudante demonstra entusiasmo e comprometimento com o projeto?\n• Demonstra capacidade para analisar criticamente dados e informacoes?\n• Compreende diferentes pontos de vista e situacoes novas?\n• Reconhece os limites do proprio projeto?\n• Consegue comparar sua experiencia com trabalhos semelhantes?\n• Demonstrou iniciativa, perseveranca, planejamento e capacidade de articulacao?\n• Conseguiu envolver familia, escola ou comunidade no desenvolvimento do projeto?',
   1),
  (4, 'Profundidade da Pesquisa', 2.00,
   E'• O problema estudado foi resolvido?\n• O estudante apresenta documentacao do desenvolvimento do trabalho (diario de bordo, relatorio)?\n• A documentacao registra detalhadamente as atividades realizadas?\n• Ha evidencias de planejamento e organizacao?\n• As dificuldades encontradas e suas solucoes foram registradas?\n• Existem comentarios ou feedback do orientador?\n• Houve atualizacoes regulares durante o desenvolvimento da pesquisa?',
   1),
  (5, 'Clareza e Objetividade na Exposicao do Projeto', 1.00,
   E'• Durante a apresentacao o estudante demonstra seguranca e dominio do conteudo?\n• A apresentacao oral foi organizada e coerente?\n• O material escrito demonstra conhecimento sobre o projeto?\n• As etapas do desenvolvimento foram apresentadas de forma clara e organizada?',
   1),
  (6, 'Relevancia Social e Ambiental', 1.00,
   E'• O problema estudado esta relacionado ao contexto social do estudante?\n• O projeto possui potencial para transformar a realidade da comunidade?\n• Foram adotadas praticas de reciclagem ou reutilizacao de materiais?\n• O trabalho promove educacao e conscientizacao ambiental?\n• O projeto possui potencial de aplicacao pratica?',
   1),
  (7, 'Criatividade e Originalidade', 1.00,
   E'• O trabalho apresenta uma proposta inovadora?\n• A ideia desenvolvida e original e demonstra autenticidade?\n• Os estudantes apresentaram solucoes ou abordagens diferenciadas em relacao ao tema?',
   2),
  (8, 'Fundamentacao e Pesquisa', 1.00,
   E'• Os estudantes demonstram dominio do tema apresentado?\n• O trabalho evidencia pesquisa consistente sobre aspectos historicos, culturais, cientificos ou tecnologicos relacionados ao tema?\n• As informacoes apresentadas sao claras, corretas e bem fundamentadas?',
   2),
  (9, 'Inclusao, Relevancia Social e Ambiental', 1.00,
   E'• O trabalho adotou praticas de reciclagem, reutilizacao ou uso consciente de materiais?\n• O projeto valoriza a cultura local, regional, nacional ou outras manifestacoes culturais?\n• O trabalho considera aspectos de acessibilidade e inclusao para diferentes publicos?\n• A proposta demonstra relevancia social e/ou ambiental?',
   2),
  (10, 'Impacto Visual e Qualidade Tecnica', 1.00,
   E'• O trabalho apresenta boa qualidade visual e organizacao estetica?\n• A apresentacao desperta o interesse e a atencao do publico?\n• Os estudantes demonstram dominio das tecnicas utilizadas (desenho, pintura, fotografia, musica, maquete, prototipo, entre outras)?\n• Os materiais e recursos empregados foram utilizados de forma adequada?',
   2),
  (11, 'Interdisciplinaridade', 1.00,
   E'• O trabalho integra conhecimentos de diferentes areas?\n• As diferentes areas do conhecimento estao articuladas de forma coerente?\n• A interdisciplinaridade contribui para enriquecer a compreensao do tema e a qualidade da proposta?',
   2)
ON CONFLICT DO NOTHING;

SELECT setval(pg_get_serial_sequence('public.criterios', 'id'), 11);
